Container base image
evalf/nutils pull request #710
Opened 2022-09-01 20:46 UTC by joostvanzwieten

2022-09-02 15:11 UTC, gertjanvanzwieten requested changes

2022-09-02 15:11 UTC, gertjanvanzwieten commented on devtools/container/build.py
> +rev = args.revision
removing HEAD here seems incompatible with leaving revision unspecified above.

2022-09-02 15:11 UTC, gertjanvanzwieten commented on devtools/container/build_base.py
> +    container.run('apt', 'install', '-y', '--no-install-recommends', 'python3', 'python3-pip', 'python3-wheel', 'python3-ipython', 'python3-numpy', 'python3-scipy', 'python3-matplotlib', 'python3-pil
let's move meshio to the nutils image

2022-09-02 20:15 UTC, joostvanzwieten commented on devtools/container/build.py
> +rev = args.revision
fixed

2022-09-02 20:16 UTC, joostvanzwieten commented on devtools/container/build_base.py
> +    container.run('apt', 'install', '-y', '--no-install-recommends', 'python3', 'python3-pip', 'python3-wheel', 'python3-ipython', 'python3-numpy', 'python3-scipy', 'python3-matplotlib', 'python3-pil
done

2022-09-03 08:13 UTC, gertjanvanzwieten approved these changes

2022-09-03 08:14 UTC, merged